services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $pluginDirectory: '%plugin.directory%'
      $pluginName: '%plugin.name%'
      $pluginVersion: '%plugin.version%'
      $cronLogger: '@logger.cron'
      $rootPath: '%runtime.root_dir%'

  _instanceof:
    LoxBerryPoppins\Cron\CronJobInterface:
      tags: ['plugin.cron_job']
    LoxBerryPoppins\Frontend\AbstractController:
      tags: ['plugin.controller']
    Twig\Extension\AbstractExtension:
      tags: ['twig.extension']

  LoxBerryPoppins\:
    resource: '../src/*'

  LoxBerry\:
    resource: '../../loxberry-core/src/*'

  LoxBerryPoppins\Frontend\Routing\PageRouterInterface:
    class: LoxBerryPoppins\Frontend\Routing\PageRouter
    public: true

  LoxBerry\Logging\Database\LogFileDatabase:
    factory: '@LoxBerry\Logging\Database\LogFileDatabaseFactory'

  Twig\Environment:
    class: 'Twig\Environment'
    factory: '@LoxBerryPoppins\Frontend\Twig\TwigEnvironmentFactory'

  logger.cron:
    class: 'LoxBerry\Logging\Logger'
    factory: '@LoxBerryPoppins\Cron\CronLoggerFactory'

  LoxBerryPoppins\Cron\CronJobRunner:
    public: true
    arguments:
      $cronJobs: !tagged plugin.cron_job

  LoxBerryPoppins\Frontend\Routing\ControllerExecutor:
    arguments:
      $controllers: !tagged plugin.controller

  LoxBerryPoppins\Frontend\Twig\TwigEnvironmentFactory:
    arguments:
      $extensions: !tagged twig.extension
