services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $packageDirectory: '%plugin.directory%'
      $packageName: '%plugin.name%'
      $cronLogger: '@logger.cron'
      $rootPath: '%runtime.root_dir%'

  _instanceof:
    LoxBerryPoppins\Cron\CronJobInterface:
      tags: ['plugin.cron_job']
    LoxBerryPoppins\Frontend\AbstractController:
      tags: ['plugin.controller']
    Twig\Extension\AbstractExtension:
      tags: ['twig.extension']

  LoxBerryPoppins\:
    resource: '../src/*'

  LoxBerry\:
    resource: '../../loxberry-core/src/*'

  LoxBerryPoppins\Frontend\Routing\PageRouterInterface:
    class: LoxBerryPoppins\Frontend\Routing\PageRouter
    public: true

  LoxBerry\Logging\Database\LogFileDatabase:
    factory: '@LoxBerry\Logging\Database\LogFileDatabaseFactory'

  Twig\Environment:
    class: 'Twig\Environment'
    factory: '@LoxBerryPoppins\Frontend\Twig\TwigEnvironmentFactory'

  logger.cron:
    class: 'LoxBerry\Logging\Logger'
    factory: '@LoxBerryPoppins\Cron\CronLoggerFactory'
